# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Instagram2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Parse'


  # Pods for Instagram2

  target 'Instagram2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Instagram2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
